In [1]:
import os
import gymnasium as gym
import numpy as np

import torch.nn as nn

from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize, SubprocVecEnv
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3 import PPO

from stable_baselines3.common.utils import set_random_seed

In [11]:
from stable_baselines3.common.env_util import unwrap_wrapper, is_wrapped

In [2]:
seed = 42

env = make_vec_env('Hopper-v4', n_envs=16, seed=seed, vec_env_cls=DummyVecEnv, wrapper_class=Auto_DR_Wrapper, wrapper_kwargs=dr_quarks_hopper)

#print(env.envs[0].model.body('torso').mass) # 1 is the second environment

randomize_fn = env.env_method('sample_task')
set_task_fn = env.get_attr('set_task')
print('rand fn', randomize_fn)
print('set fn', set_task_fn)

for i in range(len(randomize_fn)):
    print("set task i:", set_task_fn[i])
    print("randomize i:", randomize_fn[i])
    set_task_fn[i](randomize_fn[i])

NameError: name 'Auto_DR_Wrapper' is not defined

In [19]:
unwrap_wrapper(env._get_target_envs(0), HopperEnv)

NameError: name 'HopperEnv' is not defined

In [22]:
env._get_target_envs(0)[0].unwrapped.spec.id

'Hopper-v4'

In [23]:
name = env.envs[0].unwrapped.spec.id
name

'Hopper-v4'

In [27]:
env = make_vec_env('HalfCheetah-v4', n_envs=16, seed=seed, vec_env_cls=DummyVecEnv)

print(env.get_attr('model')[0].body_mass) 
print(env.get_attr('model')[0].geom_friction)
print(env.get_attr('model')[0].dof_damping)
#print(env.get_attr('model')[0].pair_friction)


print(env.envs[0].unwrapped.model.geom_friction)

[0.         6.25020921 1.54351464 1.5874477  1.09539749 1.43807531
 1.20083682 0.88451883]
[[0.4 0.1 0.1]
 [0.4 0.1 0.1]
 [0.4 0.1 0.1]
 [0.4 0.1 0.1]
 [0.4 0.1 0.1]
 [0.4 0.1 0.1]
 [0.4 0.1 0.1]
 [0.4 0.1 0.1]
 [0.4 0.1 0.1]]
[0.  0.  0.  6.  4.5 3.  4.5 3.  1.5]


AttributeError: 'list' object has no attribute 'unwrapped'

In [8]:
seed = 42

env = make_vec_env('Ant-v4', n_envs=16, seed=seed, vec_env_cls=DummyVecEnv)

print(env.get_attr('model')[0].body_mass) 
print(env.get_attr('model')[0].geom_friction)
print(env.get_attr('model')[0].dof_damping)

[0.         0.32724923 0.03915775 0.03915775 0.0675922  0.03915775
 0.03915775 0.0675922  0.03915775 0.03915775 0.0675922  0.03915775
 0.03915775 0.0675922 ]
[[1.  0.5 0.5]
 [1.  0.5 0.5]
 [1.  0.5 0.5]
 [1.  0.5 0.5]
 [1.  0.5 0.5]
 [1.  0.5 0.5]
 [1.  0.5 0.5]
 [1.  0.5 0.5]
 [1.  0.5 0.5]
 [1.  0.5 0.5]
 [1.  0.5 0.5]
 [1.  0.5 0.5]
 [1.  0.5 0.5]
 [1.  0.5 0.5]]
[0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
env = make_vec_env('Humanoid-v4', n_envs=16, seed=seed, vec_env_cls=DummyVecEnv)

print(env.get_attr('model')[0].body_mass) 
print(env.get_attr('model')[0].geom_friction)
print(env.get_attr('model')[0].dof_damping)

[0.         8.90746237 2.26194671 6.61619413 4.75175093 2.75569617
 1.76714587 4.75175093 2.75569617 1.76714587 1.66108048 1.22954019
 1.66108048 1.22954019]
[[1.e+00 1.e-01 1.e-01]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]
 [1.e+00 5.e-03 1.e-04]]
[0. 0. 0. 0. 0. 0. 5. 5. 5. 5. 5. 5. 1. 5. 5. 5. 1. 1. 1. 1. 1. 1. 1.]
